from . import hr_job
from . import hr_applicant
from . import res_company
from . import res_config_settings
from . import djinni_account
from . import djinni_sync_log
from . import djinni_blank
from . import djinni_recruiter
from . import djinni_domain
from . import djinni_salary_deviation
from . import djinni_exp_year_deviation
from . import djinni_eng_level_deviation
from . import djinni_eng_level
from . import djinni_company_type
from . import djinni_category
from . import djinni_country
from . import djinni_region
from . import djinni_city
from . import djinni_remoty_type
from . import djinni_relocation
from . import djinni_experience
from . import djinni_quiz
from . import djinni_quiz_question
from . import djinni_quiz_question_type
