from odoo import api, fields, models, _


class DocumentGenerated(models.Model):
    _name = 'document.generated'
    _description = 'Generated Document'
    _inherit = ['mail.thread']
    _order = 'create_date desc'

    name = fields.Char(
        string='Reference',
        readonly=True,
        copy=False,
    )
    template_id = fields.Many2one(
        'document.template',
        string='Template',
        required=True,
        ondelete='restrict',
        tracking=True,
    )
    res_model = fields.Char(
        string='Source Model',
    )
    res_id = fields.Integer(
        string='Source Record ID',
    )
    res_name = fields.Char(
        string='Source Record',
        compute='_compute_res_name',
    )
    docx_attachment_id = fields.Many2one(
        'ir.attachment',
        string='DOCX File',
        ondelete='set null',
    )
    pdf_attachment_id = fields.Many2one(
        'ir.attachment',
        string='PDF File',
        ondelete='set null',
    )
    state = fields.Selection(
        selection=[
            ('generated', 'Generated'),
            ('error', 'Error'),
        ],
        string='Status',
        default='generated',
        tracking=True,
    )
    error_message = fields.Text(
        string='Error Details',
    )
    generated_by = fields.Many2one(
        'res.users',
        string='Generated By',
        readonly=True,
        default=lambda self: self.env.user,
    )

    @api.depends('res_model', 'res_id')
    def _compute_res_name(self):
        for rec in self:
            if rec.res_model and rec.res_id:
                try:
                    source = self.env[rec.res_model].browse(rec.res_id)
                    rec.res_name = source.display_name
                except Exception:
                    rec.res_name = False
            else:
                rec.res_name = False

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if not vals.get('name'):
                vals['name'] = self.env['ir.sequence'].next_by_code('document.generated') or _('New')
        return super().create(vals_list)

    def action_download_docx(self):
        self.ensure_one()
        if not self.docx_attachment_id:
            return False
        return {
            'type': 'ir.actions.act_url',
            'url': '/web/content/%d?download=true' % self.docx_attachment_id.id,
            'target': 'self',
        }

    def action_download_pdf(self):
        self.ensure_one()
        if not self.pdf_attachment_id:
            return False
        return {
            'type': 'ir.actions.act_url',
            'url': '/web/content/%d?download=true' % self.pdf_attachment_id.id,
            'target': 'self',
        }
