from . import test_call_stage_config
from . import test_call_template_autofill
from . import test_track_template_injection
from . import test_calendar_event_create
from . import test_payload_fields_extended
from . import test_etap1_fixes
from . import test_etap2_native_swap
from . import test_etap3_cockpit
from . import test_etap4_polish
from . import test_etap6_body_refresh
from . import test_etap7_recruiter_sync
from . import test_booking_prefill
from . import test_interviewers
from . import test_existing_booking_redirect
from . import test_candidate_attendee
