# -*- coding: utf-8 -*-

from odoo import api, fields, models, _
from odoo.exceptions import UserError


class JitoLedgerMove(models.Model):
    """Phase 4 adds two move-level features that complete FR-08 (Adjustment
    JE with two reversal modes):

      * ``reason`` — free-text justification for the adjustment, tracked
        in chatter for audit (PRD §Security Matrix tracks all actions).
      * ``is_voided`` + ``action_reverse_destructive()`` — destructive
        reversal mode. Original keeps state='posted' but is_voided=True;
        reports filter voided moves out so the entry is invisible in
        management views, while the audit trail (chatter, mail.thread)
        retains who voided and why.

    The HLD originally proposed a separate ``jito.mgt.adjustment.je``
    wrapper model. We elide it: the wrapper would carry the same metadata
    we put directly here, and the discriminator-based pattern
    (entry_type='mgt_adj_je') already gives us everything we need without
    a parallel record.
    """

    _inherit = 'jito.ledger.move'

    reason = fields.Char(
        string='Reason',
        tracking=True,
        help="Justification for this management adjustment. Required when "
             "performing destructive reversal — captured for audit.",
    )

    is_voided = fields.Boolean(
        string='Voided',
        default=False,
        copy=False,
        readonly=True,
        tracking=True,
        index=True,
        help="True iff this move was destructively reversed (FR-08 mode "
             "(a)). Voided moves are hidden from management reports but "
             "remain in the database with full audit chatter for "
             "traceability.",
    )
    voided_by_uid = fields.Many2one(
        comodel_name='res.users',
        string='Voided By',
        readonly=True,
        copy=False,
    )
    voided_at = fields.Datetime(
        string='Voided At',
        readonly=True,
        copy=False,
    )
    voided_reason = fields.Char(
        string='Void Reason',
        readonly=True,
        copy=False,
    )

    # Reference back to the semantic adjustment that generated this move.
    # Set by jito.mgt.restatement._generate_move() etc. so the move's
    # form can navigate back to the higher-level record.
    adjustment_origin = fields.Reference(
        selection=[
            ('jito.mgt.restatement', 'Restatement'),
            ('jito.mgt.bridging', 'Bridging'),
            ('jito.mgt.regrouping', 'Regrouping'),
        ],
        string='Adjustment Origin',
        readonly=True,
        copy=False,
        help="If this move was generated by a higher-level semantic "
             "adjustment (Restatement, Bridging, Regrouping), the source "
             "record is referenced here for navigation.",
    )

    # ---- FR-08 destructive reversal --------------------------------------

    def action_reverse_destructive(self, reason=None):
        """Destructive reversal — FR-08 mode (a).

        Used when the underlying event turned out to be invalid (e.g., a
        transaction that never actually happened). The move is marked
        voided; reports filter voided moves out so neither the original
        nor its effect appears in management views. Audit trail
        (chatter, voided_by_uid, voided_at, voided_reason) preserved.

        Permission: gated to ``group_mgmt_ledger_senior_accountant`` or
        above, per PRD §Security Matrix. Plain Accountants cannot run it.
        """
        if not self.env.user.has_group(
                'jito_ledger_core.group_mgmt_ledger_senior_accountant'):
            raise UserError(_(
                "Destructive reversal requires the 'Senior Accountant' or "
                "'Management Ledger Administrator' role per the security "
                "matrix. Contact an administrator if you believe this "
                "transaction is genuinely invalid."
            ))
        for move in self:
            if move.state != 'posted':
                raise UserError(_(
                    "Only posted moves can be destructively reversed; "
                    "move '%s' is %s.",
                    move.display_name, move.state,
                ))
            if move.is_voided:
                raise UserError(_(
                    "Move '%s' is already voided.", move.display_name,
                ))
            if not (reason or move.reason):
                raise UserError(_(
                    "Destructive reversal requires a reason. Fill in the "
                    "Reason field on the move first, or pass a reason "
                    "explicitly."
                ))
            move.write({
                'is_voided': True,
                'voided_by_uid': self.env.user.id,
                'voided_at': fields.Datetime.now(),
                'voided_reason': reason or move.reason,
            })
            move.message_post(body=_(
                "Move destructively reversed by %s.\nReason: %s",
                self.env.user.display_name,
                reason or move.reason,
            ))
        return True
