from odoo import models, fields, api, _
from odoo.exceptions import UserError


class ScaTransaction(models.Model):
    _name = 'sca.transaction'
    _description = 'Crypto Transaction'
    _order = 'tx_date desc, id desc'
    _inherit = ['mail.thread', 'mail.activity.mixin']

    watched_address_id = fields.Many2one(
        'sca.watched_address',
        string='Watched Address',
        required=True,
        ondelete='cascade',
        index=True,
    )
    token_id = fields.Many2one(
        'sca.token',
        string='Token',
        ondelete='set null',
        index=True,
    )
    tx_hash = fields.Char(string='Transaction Hash', required=True, index=True, copy=False)
    log_index = fields.Integer(
        string='Log Index',
        default=-1,
        help='ERC-20 event log index within the transaction. -1 for native ETH transfers.',
    )
    block_number = fields.Integer(string='Block Number', readonly=True)
    tx_date = fields.Datetime(string='Date', readonly=True)
    from_address = fields.Char(string='From Address', readonly=True)
    to_address = fields.Char(string='To Address', readonly=True)
    raw_value = fields.Char(string='Raw Value', readonly=True, help='Value in smallest token unit (wei / base units)')
    token_symbol = fields.Char(string='Token', readonly=True)
    token_contract = fields.Char(string='Token Contract', readonly=True)
    gas_used = fields.Integer(string='Gas Used', readonly=True)

    etherscan_url = fields.Char(
        string='View on Block Explorer',
        compute='_compute_etherscan_url',
        store=False,
        help="Per-network explorer URL: etherscan.io for ERC-20, "
             "tronscan.org for TRC-20 (17.0.3.0.0).",
    )
    from_explorer_url = fields.Char(
        compute='_compute_explorer_urls', store=False,
        help="Per-network explorer URL for `from_address`.",
    )
    to_explorer_url = fields.Char(
        compute='_compute_explorer_urls', store=False,
        help="Per-network explorer URL for `to_address`.",
    )
    token_contract_explorer_url = fields.Char(
        compute='_compute_explorer_urls', store=False,
        help="Per-network explorer URL for `token_contract`.",
    )
    description = fields.Text(string='Description', tracking=True)
    attachment_ids = fields.Many2many(
        'ir.attachment',
        'sca_transaction_attachment_rel',
        'transaction_id',
        'attachment_id',
        string='File Attachments',
    )

    value_decimal = fields.Float(
        string='Amount',
        compute='_compute_value_decimal',
        digits=(30, 8),
        store=True,
    )
    direction = fields.Selection(
        [('in', 'Incoming'), ('out', 'Outgoing')],
        string='Direction',
        compute='_compute_direction',
        store=True,
    )
    from_display = fields.Char(
        string='From',
        compute='_compute_display_addresses',
        store=False,
    )
    to_display = fields.Char(
        string='To',
        compute='_compute_display_addresses',
        store=False,
    )

    # ── Management-Ledger Injection (17.0.2.0.0) ──────────────────────────
    # Stock-LL injection (account.bank.statement.line) was removed in
    # 17.0.2.0.0; crypto txs now post directly into jito.ledger.move
    # (entry_type='ext_adjustment'). The ``statement_line_id`` column is
    # retained for historical data lookup but no longer written into.
    statement_line_id = fields.Many2one(
        'account.bank.statement.line',
        string='Statement Line (legacy)',
        readonly=True, copy=False,
        ondelete='set null',
        help="Historical link from the pre-17.0.2.0.0 stock-LL "
             "injection flow. Read-only; new injections use "
             "jito_move_id instead.",
    )
    jito_move_id = fields.Many2one(
        'jito.ledger.move',
        string='Management Ledger Move',
        readonly=True, copy=False,
        ondelete='set null',
        help="The jito.ledger.move(entry_type='ext_adjustment') "
             "generated by Inject to Management Ledger.",
    )
    is_injected = fields.Boolean(
        string='Injected',
        compute='_compute_is_injected', store=True,
        help="True when this crypto tx has a backing "
             "``jito.ledger.move`` with at least one line. "
             "17.0.8.5.0 — the line_ids dependency makes the field "
             "correctly flip back to False when the user empties or "
             "deletes the generated move from the ML side, so the "
             "tx becomes eligible for re-injection.",
    )
    crypto_tx_ref = fields.Char(
        string='Crypto TX Ref',
        compute='_compute_crypto_tx_ref', store=True,
        index='trigram', readonly=True, copy=False,
    )

    # 17.0.8.3.0 — dedup widened from `tx_hash` alone to the composite
    # `(tx_hash, from_address, to_address, raw_value)`. A single TRON
    # transaction can emit multiple Transfer events (DEX swaps, batch
    # payouts, contract loops); they share a tx_hash but differ in
    # at least one of from/to/amount, so the composite still rejects
    # genuine duplicates while letting all real events through.
    _sql_constraints = [
        ('unique_tx_event',
         'UNIQUE(tx_hash, from_address, to_address, raw_value)',
         'A token-transfer event with the same tx_hash, from, to, '
         'and amount already exists.'),
    ]

    @staticmethod
    def _explorer_url_for(network, kind, value):
        """Return a block-explorer URL for ``value`` of ``kind`` (one
        of 'tx', 'address', 'contract') on the given ``network``
        ('erc20' / 'trc20'). Returns False when nothing meaningful
        can be built (missing value or unsupported network).
        """
        if not value:
            return False
        network = network or 'erc20'
        if network == 'trc20':
            base = 'https://tronscan.org/#'
            return {
                'tx':       '%s/transaction/%s' % (base, value),
                'address':  '%s/address/%s'     % (base, value),
                'contract': '%s/token20/%s'     % (base, value),
            }.get(kind, False)
        # Default: ERC-20 / Ethereum mainnet via Etherscan.
        base = 'https://etherscan.io'
        return {
            'tx':       '%s/tx/%s'      % (base, value),
            'address':  '%s/address/%s' % (base, value),
            'contract': '%s/token/%s'   % (base, value),
        }.get(kind, False)

    @api.depends('tx_hash', 'watched_address_id.network')
    def _compute_etherscan_url(self):
        for rec in self:
            rec.etherscan_url = self._explorer_url_for(
                rec.watched_address_id.network, 'tx', rec.tx_hash,
            )

    @api.depends(
        'from_address', 'to_address', 'token_contract',
        'watched_address_id.network',
    )
    def _compute_explorer_urls(self):
        for rec in self:
            net = rec.watched_address_id.network
            rec.from_explorer_url = self._explorer_url_for(net, 'address', rec.from_address)
            rec.to_explorer_url = self._explorer_url_for(net, 'address', rec.to_address)
            rec.token_contract_explorer_url = self._explorer_url_for(
                net, 'contract', rec.token_contract,
            )

    # ── Open-in-explorer button actions ──────────────────────────────────

    def _open_url(self, url):
        if not url:
            from odoo.exceptions import UserError
            raise UserError(_('No explorer URL available for this field.'))
        return {'type': 'ir.actions.act_url', 'url': url, 'target': 'new'}

    def action_open_from_explorer(self):
        self.ensure_one()
        return self._open_url(self.from_explorer_url)

    def action_open_to_explorer(self):
        self.ensure_one()
        return self._open_url(self.to_explorer_url)

    def action_open_contract_explorer(self):
        self.ensure_one()
        return self._open_url(self.token_contract_explorer_url)

    def action_open_tx_explorer(self):
        self.ensure_one()
        return self._open_url(self.etherscan_url)

    @api.depends('raw_value', 'token_id')
    def _compute_value_decimal(self):
        for rec in self:
            try:
                decimals = rec.token_id.decimals if rec.token_id else 18
                rec.value_decimal = int(rec.raw_value or '0') / (10 ** decimals)
            except (ValueError, TypeError):
                rec.value_decimal = 0.0

    @api.depends('to_address', 'watched_address_id')
    def _compute_direction(self):
        for rec in self:
            watched = (rec.watched_address_id.address or '').lower()
            to_addr = (rec.to_address or '').lower()
            rec.direction = 'in' if to_addr == watched else 'out'

    @api.depends('from_address', 'to_address')
    def _compute_display_addresses(self):
        # Load all known addresses once for the batch
        known = {
            r.address.lower(): r.name
            for r in self.env['sca.known_address'].sudo().search([])
        }
        for rec in self:
            from_addr = (rec.from_address or '').lower()
            to_addr = (rec.to_address or '').lower()
            rec.from_display = known.get(from_addr, rec.from_address or '')
            rec.to_display = known.get(to_addr, rec.to_address or '')

    @api.depends('jito_move_id', 'jito_move_id.line_ids')
    def _compute_is_injected(self):
        """Inject status (17.0.8.5.0).

        Considered injected only when the back-pointer is set AND the
        target ``jito.ledger.move`` still has at least one line. This
        handles three deletion paths from the ML side:

        * Move deleted entirely → ``ondelete='set null'`` on
          ``jito_move_id`` clears the FK; ``bool(False)`` → not
          injected.
        * Move emptied (all lines deleted, shell remains) → FK still
          valid but ``line_ids`` is empty; treat as not injected so
          the user can re-inject without first having to remove the
          empty shell from the ML side.
        * Some lines deleted but not all → still injected (the move
          is broken accounting-wise, but the ML side's per-currency
          balance constraint catches that on its own).
        """
        for rec in self:
            move = rec.jito_move_id
            rec.is_injected = bool(move and move.line_ids)

    @api.depends('tx_hash', 'log_index')
    def _compute_crypto_tx_ref(self):
        for rec in self:
            if rec.tx_hash:
                rec.crypto_tx_ref = '%s_%s' % (rec.tx_hash, rec.log_index)
            else:
                rec.crypto_tx_ref = False

    # ── Accounting Injection Methods ─────────────────────────────────────

    def _find_mgt_ledger_mapping(self):
        """Find the management-ledger mapping for this transaction's
        (address, token). Returns ``sca.mgt.ledger.map`` record.
        """
        self.ensure_one()
        return self.env['sca.mgt.ledger.map'].search([
            ('watched_address_id', '=', self.watched_address_id.id),
            ('token_symbol', '=', self.token_symbol),
        ], limit=1)

    def _crypto_tx_payload(self):
        """Build the ``crypto_tx`` payload dict per
        ``jito_ledger_adjustments/payload_schemas.py`` v1. Stored as
        JSON on the trace row's ``source_payload`` field.
        """
        self.ensure_one()
        return {
            'tx_hash': self.tx_hash,
            'token': self.token_symbol,
            'amount_decimal': self.value_decimal,
            'direction': self.direction,
            'block_number': self.block_number,
            'wallet_address': self.watched_address_id.address,
        }

    def _find_partner_for_transaction(self):
        """Best-effort partner matching via known address alias."""
        self.ensure_one()
        Partner = self.env['res.partner']

        # Counterparty is the "other" address
        counterparty = self.from_address if self.direction == 'in' else self.to_address
        if not counterparty:
            return Partner

        # Look up in known addresses
        known = self.env['sca.known_address'].sudo().search([
            ('address', '=ilike', counterparty),
        ], limit=1)
        if known:
            partner = Partner.search([
                ('name', 'ilike', known.name),
                ('is_company', '=', True),
            ], limit=1)
            if partner:
                return partner

        return Partner

    def action_inject_to_management_ledger(self):
        """Create one ``jito.ledger.move(entry_type='ext_adjustment')``
        per selected crypto transaction (17.0.2.0.0).

        Each generated move has two balanced lines in the token's
        currency:

          * Inbound (direction='in'): DR asset_account + CR counterpart.
          * Outbound (direction='out'): CR asset_account + DR counterpart.

        Each line gets a ``jito.ledger.trace`` row with
        ``source_payload_kind='crypto_tx'`` carrying the tx hash, token,
        amount, direction, block_number, and wallet_address — the
        provenance an auditor can query.
        """
        Move = self.env['jito.ledger.move'].sudo()
        Line = self.env['jito.ledger.move.line'].sudo()
        Trace = self.env['jito.ledger.trace'].sudo()

        injected = 0
        skipped = 0
        errors = []
        for rec in self:
            if rec.jito_move_id:
                skipped += 1
                continue
            if not rec.value_decimal:
                skipped += 1
                continue
            mapping = rec._find_mgt_ledger_mapping()
            if not mapping:
                errors.append('%s: no management-ledger mapping for %s / %s' % (
                    rec.tx_hash[:10],
                    rec.watched_address_id.name,
                    rec.token_symbol,
                ))
                continue
            if not mapping.ledger_id:
                errors.append('%s: journal %s is not bound to a management ledger' % (
                    rec.tx_hash[:10],
                    mapping.journal_id.display_name,
                ))
                continue
            # 17.0.8.0.0 — accounts + currency are now sourced from the
            # journal's Bank/Cash Configuration and the watched token,
            # respectively. The mapping is purely the (wallet, token) →
            # journal binding. Errors below point the user at the
            # exact record to edit.
            asset_account = mapping.journal_id.bank_account_id
            counterpart_account = mapping.journal_id.suspense_account_id
            currency = rec.token_id.currency_id
            missing = []
            if not asset_account:
                missing.append(
                    "Bank Account on journal '%s' (Configuration → "
                    "Journals → open it → Bank/Cash Configuration "
                    "group)" % mapping.journal_id.display_name
                )
            if not counterpart_account:
                missing.append(
                    "Suspense Account on journal '%s' (same tab)"
                    % mapping.journal_id.display_name
                )
            if not currency:
                missing.append(
                    "Currency on watched token '%s' (open the watched "
                    "address → Watched Tokens → re-pick the preset to "
                    "auto-fill it)" % (rec.token_id.name or '?')
                )
            if missing:
                errors.append('%s: %s' % (
                    rec.tx_hash[:10], '; '.join(missing),
                ))
                continue
            partner = rec._find_partner_for_transaction()
            tx_date = rec.tx_date.date() if rec.tx_date else fields.Date.context_today(rec)
            amount = rec.value_decimal  # always positive magnitude
            # Sign convention: inbound credits asset_account-side as a
            # debit (assets up), counterpart as a credit. Outbound
            # mirrors. amount_currency on jito.ledger.move.line is
            # positive=debit, negative=credit (HLD Decision #8).
            if rec.direction == 'in':
                asset_signed = amount
                counterpart_signed = -amount
            else:
                asset_signed = -amount
                counterpart_signed = amount
            direction_label = 'Received' if rec.direction == 'in' else 'Sent'
            line_label = '%s %s %s' % (direction_label, amount, rec.token_symbol)
            try:
                move = Move.create({
                    'journal_id': mapping.journal_id.id,
                    'ledger_id': mapping.ledger_id.id,
                    'entry_type': 'ext_adjustment',
                    'date': tx_date,
                    'partner_id': partner.id if partner else False,
                    'currency_id': currency.id,
                    'ref': 'Crypto %s' % rec.crypto_tx_ref,
                    'state': 'draft',
                    'name': _('New'),
                })
                payload = rec._crypto_tx_payload()
                asset_line = Line.create({
                    'move_id': move.id,
                    'account_id': asset_account.id,
                    'partner_id': partner.id if partner else False,
                    'name': line_label,
                    'currency_id': currency.id,
                    'amount_currency': asset_signed,
                })
                counterpart_line = Line.create({
                    'move_id': move.id,
                    'account_id': counterpart_account.id,
                    'partner_id': partner.id if partner else False,
                    'name': line_label,
                    'currency_id': currency.id,
                    'amount_currency': counterpart_signed,
                })
                for line in (asset_line, counterpart_line):
                    Trace.create({
                        'parallel_line_id': line.id,
                        'source_line_id': False,
                        'source_payload_kind': 'crypto_tx',
                        'source_payload': payload,
                        'kind': 'derives_from',
                        'weight': 1.0,
                    })
                move.action_post()
                rec.sudo().jito_move_id = move.id
                injected += 1
            except Exception as e:
                errors.append('%s: %s' % (rec.tx_hash[:10], str(e)[:120]))

        msg_parts = ['%d/%d transactions injected to management ledger.' % (
            injected, len(self),
        )]
        if skipped:
            msg_parts.append('%d skipped (already injected or zero value).' % skipped)
        if errors:
            msg_parts.append('%d errors: %s' % (len(errors), '; '.join(errors[:3])))
            if len(errors) > 3:
                msg_parts.append('... and %d more.' % (len(errors) - 3))
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('Inject to Management Ledger'),
                'message': ' '.join(msg_parts),
                'type': 'success' if injected and not errors else ('warning' if errors else 'info'),
                'sticky': bool(errors),
            },
        }

    def action_remove_from_management_ledger(self):
        """Reverse an injection: reset the generated jito.ledger.move
        to draft, unlink it (lines + traces cascade), and clear
        ``jito_move_id`` on the transaction. Refuses if the generated
        move was further manipulated (reversed or destructively voided).
        """
        removed = 0
        warnings = []
        for rec in self:
            move = rec.jito_move_id.sudo()
            if not move:
                continue
            if move.state == 'reversed' or move.reversal_move_ids:
                warnings.append('%s: move %s has been reversed; cannot wipe' % (
                    rec.tx_hash[:10], move.display_name,
                ))
                continue
            if move.is_voided:
                warnings.append('%s: move %s is voided; cannot wipe' % (
                    rec.tx_hash[:10], move.display_name,
                ))
                continue
            try:
                if move.state == 'posted':
                    move.action_draft()
                move.unlink()
                rec.sudo().jito_move_id = False
                removed += 1
            except Exception as e:
                warnings.append('%s: %s' % (rec.tx_hash[:10], str(e)[:120]))
        msg_parts = ['%d management-ledger move(s) removed.' % removed]
        if warnings:
            msg_parts.append(' | '.join(warnings[:3]))
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('Remove from Management Ledger'),
                'message': ' '.join(msg_parts),
                'type': 'success' if removed and not warnings else 'warning',
                'sticky': bool(warnings),
            },
        }
