{
    'name': 'Secrets Manager',
    'version': '17.0.1.14.0',
    'category': 'Extra Rights/Secrets Manager',
    'summary': 'Encrypted vault for storing and sharing sensitive credentials',
    'author': 'JITO LTD',
    'website': 'https://jito.dev',
    'license': 'LGPL-3',
    'depends': ['base', 'web', 'mail'],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'views/secret_vault_views.xml',
        'views/secret_tag_views.xml',
        'views/secret_entry_views.xml',
        'views/secret_share_views.xml',
        'views/secret_audit_log_views.xml',
        'views/menus.xml',
        'wizards/unseal_wizard_views.xml',
        'wizards/change_passphrase_wizard_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'jito_secrets_manager/static/src/xml/secret_payload_widget.xml',
            'jito_secrets_manager/static/src/xml/secret_list_view.xml',
            'jito_secrets_manager/static/src/xml/create_secret_action.xml',
            'jito_secrets_manager/static/src/js/secret_payload_widget.js',
            'jito_secrets_manager/static/src/js/secret_list_view.js',
            'jito_secrets_manager/static/src/js/create_secret_action.js',
            'jito_secrets_manager/static/src/scss/secrets_manager.scss',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
