{
    'name': "Payroll Contractors Info",
    'version': '17.0.1.58.0',
    'category': 'Human Resources/Payroll',
    'summary': "Manage contractor legal entities and payment methods",
    'author': 'JITO LTD',
    'license': 'LGPL-3',
    'depends': ['hr_payroll_for_contractors', 'hr_payroll_ua_pe', 'hpc_revolut_payments', 'jito_document_template', 'sign'],
    'post_migrate': 'hooks.post_migrate_hook',
    'data': [
        'security/ir.model.access.csv',
        'security/hpc_contractor_invoice_rules.xml',
        'data/sequences.xml',
        'data/hpc_service_agreement_context_types.xml',
        'views/hpc_contractor_legal_entity_views.xml',
        'views/hpc_contractor_payment_method_views.xml',
        'views/hpc_contractor_views.xml',
        'views/hpc_contract_extension_views.xml',
        'views/hpc_contract_service_agreement_views.xml',
        'views/hpc_res_company_views.xml',
        'views/hpc_contract_templates_views.xml',
        'views/hpc_contractor_invoice_views.xml',
        'views/hpc_service_agreement_views.xml',
        'views/hpc_salary_run_ext_views.xml',
        'views/hpc_contractor_menus.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
